### ISSUE TITLE
X Error of failed request:  BadValue (integer parameter out of range for operation)

### ISSUE THREAD

**Issue by robbeofficial** [webanck/docker-wine-steam#13]
running Ubuntu 16.04.2 LTS and nvidia driver 375.39 (GTX 1070) on host.

steam prints the following output and terminates:

wine@tuxedo:~$ steam 
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[2017-05-13 12:42:43] Startup - updater built Apr 25 2017 15:46:19
Looks like steam didn't shutdown cleanly, scheduling immediate update check
[2017-05-13 12:42:43] Checking for update on startup
[2017-05-13 12:42:43] Checking for available update...
[2017-05-13 12:42:44] Download skipped: /client/steam_client_win32 version 1493162727, installed version 1493162727
[2017-05-13 12:42:44] Nothing to do
[2017-05-13 12:42:44] Verifying installation...
[2017-05-13 12:42:44] Performing checksum verification of executable files
[2017-05-13 12:42:44] Verification complete
[0513/124244:ERROR:network_change_notifier_win.cc(170)] WSALookupServiceBegin failed with: 8
[0513/124244:ERROR:dns_config_service_win.cc(584)] DNS registry watch failed to start.
IPC client is in my process, could/should be using an in-process pipe. shm_unlink(/pulse-shm-1705972837) failed: No such file or directory
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  1170
  Current serial number in output stream:  1171

**Comment by pwaller** [comment]
I scoured the internet on this issue. *I am not running docker-wine*, but I did have this exact problem. I found lots of things which seem to boil down to "If you're getting BadValue / X_GLXCreateContext" then 32-bit OpenGL is not working. I was a little skeptical since I was just running the official nvidia binary.

Nonetheless, I upgraded from 375 to 384, and subsequently it just works.

I suspect this may not be enough, since it might well depend on what shared objects are visible to wine within the container. But at least there are some ideas for you to go on.

**Comment by webanck** [comment]
When looking for an answer to issue #12, I stumbled on an explanation for some of the X errors.
Again, it's caused by a shared memory issue but with the X server this time.
Following [this](https://github.com/suchja/wine/issues/8) I added the option `--ipc="host"` to the launcher.
Following [this](https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation) I added the options `--device=/dev/nvidiactl --device=/dev/nvidia-uvm --device=/dev/nvidia0` to the launcher.
A variant would be to use the option `--privileged` but it would violate containerization even more.
I also updated wine and the nvidia driver in the Dockerfile, so it should work better now.
