### ISSUE TITLE
Build Not Working

### ISSUE THREAD

**Issue by danjump** [webanck/docker-wine-steam#3]
Hey,

I'm attempting to build your package but it fails. it seems to be giving many errors associated with a bad connection with ubuntu archives. Here is an example:

 ---> Running in 07e80aeacbe7
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.

not sure what's going on with this. do you have any suggestions. Thanks!

**Comment by webanck** [comment]
Hello and thanks for trying my little tool!
As you said the building process seems to be unable to reach the ubuntu repositories and even to build the ubuntu image that my own image is based on.
Unfortunately it's a Docker relative issue, are you sure the installation of Docker went well and have you rebooted your computer since?
Any information about your linux distribution would also be appreciated.
