### ISSUE TITLE
Running on Mac OS X

### ISSUE THREAD

**Issue by alicoding** [webanck/docker-wine-steam#7]
```
./launcher.sh
Trying to run a new data container.
The container already exists, relaunching the old old one.
Error response from daemon: Mounts denied:
The paths /dev/snd and /run/user/501/pulse/native
are not shared from OS X and do not belong to the system.
You can configure shared paths from Docker -> Preferences...
```

I'm not sure how to add those 2 paths here? or does this project even supported on Mac? :)

**Comment by bugchecker** [comment]
It is not necessary to use /dev/snd and pulseaudio socket volumes together, because pulseaudio shares sound devices for multiple programs and provides alsa backend for backward compability.
I use (for my Linux containers):
```
ENV PULSE_SERVER=unix:/run/pulse/native
```
```
-v $XDG_RUNTIME_DIR/pulse:/run/pulse
```
For mac you can try to use pulseaudio over network (not over unix socket):
http://stackoverflow.com/q/40136606
http://stackoverflow.com/a/29893375
